server:
    port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
            uri: git@github.com:ajewaria/config-server.git
            searchPaths: config/config-repo
            clone-on-start: true
            default-label: master
        encrypt:
          enabled: true

  security:
    user:
      name: admin
      password: admin

encrypt:
  #key: TXlFbmNyeXB0S2V5
  key-store:
    location: classpath:key/config.jks  # Optional if using a JKS
    alias: configKey
    password: storePassword
    
