spring:
  application:
    name: USER-SERVICE
server:
  port: ${PORT:8080}  # Use 8080 if PORT is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
