spring:
    application:
        name: PRODUCT-SERVICE
server:
  port: ${PORT:8086}  # Use 8086 if PORT is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
